[profile.default]
names = true
fs_permissions = [
    { access = "read", path = "./out/" },
    { access = "read", path = "./config/" },
]
libs = ["lib"]
ignored_error_codes = ["transient-storage"]
ignored_warnings_from = ["test"]
via-ir = true
optimizer = true
optimizer_runs = 999999
bytecode_hash = "none"
evm_version = "cancun"

[profile.default.fuzz]
runs = 64

[profile.default.fmt]
wrap_comments = true

[lint]
exclude_lints = [
    "unsafe-typecast",
    "unaliased-plain-import",
    "unused-import",
    "mixed-case-variable",
    "screaming-snake-case-const",
    "erc20-unchecked-transfer",
    "unwrapped-modifier-logic",
    "mixed-case-function",
]

[rpc_endpoints]
ethereum = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
tenderly = "https://rpc.tenderly.co/fork/${TENDERLY_FORK_ID}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
