name: Install repository and cache

runs:
  using: composite

  steps:
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1

    - name: Restore forge compilation cache
      uses: actions/cache/restore@v4
      with:
        path: |
          cache
          out
        key: forge-${{ github.ref_name }}
        restore-keys: |
          forge-${{ github.base_ref }}
          forge-
